### ISSUE TITLE
Arrêt du serveur zigbee2mqtt après lancement

### ISSUE THREAD

**Issue by spottier88** [mrgreenfr/JeedomPlugins_Docs#3]
Salut et merci du boulot.
Je viens d'installer le plugin zigbee2mqtt en beta.
J'avais déjà tout configuré sur zigbee2mqtt avec jmqtt avant l'install du plugin.

Mes actions :
- Desactivation de jmqtt
- Installation du plugin zigbee2mqtt avec installation de la config complète.
- lancement des dépendances : Ok
- Le démon se lance
- et s'arrête.
Rien dans les logs, y compris en mode verbeux.

J'ai raté un truc ?

[2021-04-03 10:00:13][INFO] : ############ Démarrage des service ############
[2021-04-03 10:00:13][INFO] : ##### Démarrage du service MQTT #####
[2021-04-03 10:00:15][INFO] : ##### Démarrage du service Client MQTT (Client MQTT Local)#####
[2021-04-03 10:00:16][INFO] : ##### Le service Client MQTT a démarré (Client MQTT Local) #####
[2021-04-03 10:00:16][INFO] : ##### Le service Client MQTT ([Aucun][Client MQTT Local]) s'est connecté. #####
[2021-04-03 10:00:16][DEBUG] : [Aucun][Client MQTT Local] : Client MQTT subscribe : 1
[2021-04-03 10:00:16][DEBUG] : [Aucun][Client MQTT Local] : Jeedom-->MQTT, topic=zigbee2mqtt/bridge/request/options, json={"options":{"mqtt":{"include_device_information":true}}}
[2021-04-03 10:00:17][INFO] : ##### Démarrage du service Zigbee2MQTT #####
[2021-04-03 10:00:18][INFO] : ##### Le service zigbee2mqtt a démarré #####
[2021-04-03 10:00:23][ERROR] : ##### Le service zigbee2mqtt est arrêté #####
[2021-04-03 10:02:30][INFO] : ##### Démarrage du service Zigbee2MQTT #####
[2021-04-03 10:02:30][INFO] : ##### Démarrage du service Zigbee2MQTT #####
[2021-04-03 10:02:36][INFO] : ##### Le service zigbee2mqtt a démarré #####
[2021-04-03 10:02:41][ERROR] : ##### Le service zigbee2mqtt est arrêté #####
[2021-04-03 10:02:41][ERROR] : ##### Le service zigbee2mqtt est arrêté #####

**Comment by spottier88** [comment]
En complément, le log de zigbee2mqtt sur raspi 4

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.18.2~prestart: zigbee2mqtt@1.18.2
6 info lifecycle zigbee2mqtt@1.18.2~start: zigbee2mqtt@1.18.2
7 verbose lifecycle zigbee2mqtt@1.18.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.18.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr$
9 verbose lifecycle zigbee2mqtt@1.18.2~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.18.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.18.2~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.18.2~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.18.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid zigbee2mqtt@1.18.2
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.10.11-v7l+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.18.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.18.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

si cela peut aider

**Comment by spottier88** [comment]
Résolu en lancant un npm rebuild.
